# Generated by Django 2.1.5 on 2020-01-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Charity', max_length=254)),
                ('description', models.TextField()),
                ('donation', models.DecimalField(decimal_places=0, default=5, max_digits=1)),
                ('image', models.ImageField(upload_to='donations')),
            ],
            options={
                'verbose_name': 'Proposed Charity',
                'verbose_name_plural': 'Proposed Charities',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(default='Donor', max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Donation',
                'verbose_name_plural': 'User Donations',
            },
        ),
        migrations.CreateModel(
            name='DonationLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Charity')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Donation')),
            ],
        ),
    ]
