# Generated by Django 2.1.7 on 2019-03-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190316_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image',
            field=models.ImageField(default='static/img/portraits/default.jpg', upload_to='portraits/'),
        ),
    ]
