# Generated by Django 2.1.5 on 2019-12-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190317_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image',
            field=models.ImageField(default='portraits/default.jpg', upload_to='portraits/'),
        ),
    ]
