# Generated by Django 2.1.7 on 2019-03-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='portraits/'),
        ),
    ]
