# Generated by Django 2.1.7 on 2019-03-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190316_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='status',
            new_name='phase',
        ),
    ]
